# Data Preparation
Now that I've got the data, I have to clean it in a way that I can explore and model on it. This will require an understanding of what the columns represent, versus what I will need in the final product.

In [1]:
# Data Science Libraries
import pandas as pd

# Import my own functions
import wrangle

# Block Warning Boxes
import warnings
warnings.filterwarnings("ignore")

# Remove Limits On Viewing Dataframes
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In response to my time constraint for this project, I will reduce my data to just twins_raw data for now. I will keep the code for exploring all the data, including `twins_rawevent` and `twins_config` for another time.

#### TWINS raw data
>This data product contains TWINS raw science data downloaded from the spacecraft in
continuous mode. This includes Air Temperature Sensor PT1000 raw values, Wind Sensor
counters and temperatures, and ASIC temperature.

In [2]:
# Acquiring the data using functions in wrangle
df = wrangle.twins_raw_data()

Reading Data from local file...

In [3]:
# How big is this dataframe?
df.shape

(2350436, 63)

In [4]:
# What does it look like?
df.head()

,AOBT,SCLK,LMST,LTST,UTC,BMY_2L_TEMP_1,BMY_2L_TEMP_2,BMY_2L_TEMP_3,BMY_2L_TEMP_4,BMY_2L_TEMP_4_AVERAGE,BMY_2L_TEMP_4_STD,BMY_2L_TEMP_5,BMY_2L_TEMP_6,BMY_AIR_TEMP,BMY_AIR_TEMP_AVERAGE,BMY_AIR_TEMP_STD,BMY_WD_REF_OUT_1,BMY_WD_REF_OUT_2,BMY_WD_REF_OUT_3,BMY_WD_OUT_1,BMY_WD_OUT_2,BMY_WD_OUT_3,BMY_WD_OUT_4,BMY_WD_OUT_5,BMY_WD_OUT_6,BMY_WD_OUT_7,BMY_WD_OUT_8,BMY_WD_OUT_9,BMY_WD_OUT_10,BMY_WD_OUT_11,BMY_WD_OUT_12,BMY_WIND_FREQUENCY,BMY_AIR_TEMP_FREQUENCY,BMY_ASIC_TEMP,BPY_2L_TEMP_1,BPY_2L_TEMP_2,BPY_2L_TEMP_3,BPY_2L_TEMP_4,BPY_2L_TEMP_5,BPY_2L_TEMP_5_AVERAGE,BPY_2L_TEMP_5_STD,BPY_2L_TEMP_6,BPY_AIR_TEMP,BPY_AIR_TEMP_AVERAGE,BPY_AIR_TEMP_STD,BPY_WD_REF_OUT_1,BPY_WD_REF_OUT_2,BPY_WD_REF_OUT_3,BPY_WD_OUT_1,BPY_WD_OUT_2,BPY_WD_OUT_3,BPY_WD_OUT_4,BPY_WD_OUT_5,BPY_WD_OUT_6,BPY_WD_OUT_7,BPY_WD_OUT_8,BPY_WD_OUT_9,BPY_WD_OUT_10,BPY_WD_OUT_11,BPY_WD_OUT_12,BPY_WIND_FREQUENCY,BPY_AIR_TEMP_FREQUENCY,BPY_ASIC_TEMP
0,596876952.0,5.968612e+08,00004M06:46:33.826,00004 06:05:41,2018-334T14:46:55.755Z,-4353.0,-4645.0,-4778.0,-5006.0,NaN,NaN,-4512.0,1002.0,-5703.0,NaN,NaN,4369.0,5167.0,5599.0,648.0,662.0,648.0,1687.0,3360.0,1109.0,1019.0,1229.0,868.0,2451.0,760.0,663.0,1.0,1.0,8485.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,596876953.0,5.968612e+08,00004M06:46:34.799,00004 06:05:42,2018-334T14:46:56.755Z,-4415.0,-4723.0,-4870.0,-5099.0,NaN,NaN,-4600.0,936.0,-5776.0,NaN,NaN,4274.0,5108.0,5524.0,867.0,379.0,828.0,1033.0,10.0,551.0,578.0,324.0,637.0,418.0,526.0,492.0,1.0,1.0,8488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,596876954.0,5.968612e+08,00004M06:46:35.772,00004 06:05:43,2018-334T14:46:57.755Z,-4424.0,-4727.0,-4861.0,-5107.0,NaN,NaN,-4613.0,930.0,-5803.0,NaN,NaN,4301.0,5100.0,5532.0,713.0,521.0,641.0,1085.0,1194.0,855.0,807.0,918.0,859.0,1233.0,741.0,661.0,1.0,1.0,8491.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,596876955.0,5.968612e+08,00004M06:46:36.746,00004 06:05:44,2018-334T14:46:58.755Z,-4409.0,-4722.0,-4859.0,-5109.0,NaN,NaN,-4603.0,916.0,-5771.0,NaN,NaN,4297.0,5111.0,5539.0,687.0,578.0,662.0,1028.0,1254.0,861.0,857.0,991.0,879.0,1190.0,717.0,689.0,1.0,1.0,8494.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,596876956.0,5.968612e+08,00004M06:46:37.719,00004 06:05:45,2018-334T14:46:59.755Z,-4424.0,-4728.0,-4873.0,-5107.0,NaN,NaN,-4610.0,922.0,-5754.0,NaN,NaN,4296.0,5113.0,5535.0,438.0,284.0,599.0,862.0,1085.0,748.0,969.0,1049.0,813.0,1097.0,417.0,443.0,1.0,1.0,8498.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# What do my columns look like
df.info(null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2350436 entries, 0 to 4443
Data columns (total 63 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   AOBT                    2350436 non-null  float64
 1   SCLK                    2350436 non-null  float64
 2   LMST                    2350436 non-null  object
 3   LTST                    2350436 non-null  object
 4   UTC                     2350436 non-null  object
 5   BMY_2L_TEMP_1           1440001 non-null  float64
 6   BMY_2L_TEMP_2           1440001 non-null  float64
 7   BMY_2L_TEMP_3           1440001 non-null  float64
 8   BMY_2L_TEMP_4           707662 non-null   float64
 9   BMY_2L_TEMP_4_AVERAGE   732324 non-null   float64
 10  BMY_2L_TEMP_4_STD       732324 non-null   float64
 11  BMY_2L_TEMP_5           1440001 non-null  float64
 12  BMY_2L_TEMP_6           1440001 non-null  float64
 13  BMY_AIR_TEMP            707662 non-null   float64
 14  BMY_AIR_TEMP_AVERAGE    732324 non-null   float64
 15  BMY_AIR_TEMP_STD        732324 non-null   float64
 16  BMY_WD_REF_OUT_1        1440001 non-null  float64
 17  BMY_WD_REF_OUT_2        1440001 non-null  float64
 18  BMY_WD_REF_OUT_3        1438393 non-null  float64
 19  BMY_WD_OUT_1            1440001 non-null  float64
 20  BMY_WD_OUT_2            1440001 non-null  float64
 21  BMY_WD_OUT_3            1440001 non-null  float64
 22  BMY_WD_OUT_4            1440001 non-null  float64
 23  BMY_WD_OUT_5            1438977 non-null  float64
 24  BMY_WD_OUT_6            1440001 non-null  float64
 25  BMY_WD_OUT_7            1440001 non-null  float64
 26  BMY_WD_OUT_8            1440001 non-null  float64
 27  BMY_WD_OUT_9            1440001 non-null  float64
 28  BMY_WD_OUT_10           1440001 non-null  float64
 29  BMY_WD_OUT_11           1439417 non-null  float64
 30  BMY_WD_OUT_12           1440001 non-null  float64
 31  BMY_WIND_FREQUENCY      1440001 non-null  float64
 32  BMY_AIR_TEMP_FREQUENCY  1440001 non-null  float64
 33  BMY_ASIC_TEMP           1439999 non-null  float64
 34  BPY_2L_TEMP_1           1439206 non-null  float64
 35  BPY_2L_TEMP_2           1439206 non-null  float64
 36  BPY_2L_TEMP_3           1438217 non-null  float64
 37  BPY_2L_TEMP_4           1439241 non-null  float64
 38  BPY_2L_TEMP_5           706931 non-null   float64
 39  BPY_2L_TEMP_5_AVERAGE   732275 non-null   float64
 40  BPY_2L_TEMP_5_STD       732275 non-null   float64
 41  BPY_2L_TEMP_6           1439241 non-null  float64
 42  BPY_AIR_TEMP            706931 non-null   float64
 43  BPY_AIR_TEMP_AVERAGE    732275 non-null   float64
 44  BPY_AIR_TEMP_STD        732275 non-null   float64
 45  BPY_WD_REF_OUT_1        1439241 non-null  float64
 46  BPY_WD_REF_OUT_2        1439241 non-null  float64
 47  BPY_WD_REF_OUT_3        1439241 non-null  float64
 48  BPY_WD_OUT_1            1439241 non-null  float64
 49  BPY_WD_OUT_2            1438217 non-null  float64
 50  BPY_WD_OUT_3            1439241 non-null  float64
 51  BPY_WD_OUT_4            1439241 non-null  float64
 52  BPY_WD_OUT_5            1439241 non-null  float64
 53  BPY_WD_OUT_6            1439241 non-null  float64
 54  BPY_WD_OUT_7            1439241 non-null  float64
 55  BPY_WD_OUT_8            1439241 non-null  float64
 56  BPY_WD_OUT_9            1439241 non-null  float64
 57  BPY_WD_OUT_10           1439241 non-null  float64
 58  BPY_WD_OUT_11           1439241 non-null  float64
 59  BPY_WD_OUT_12           1439241 non-null  float64
 60  BPY_WIND_FREQUENCY      1439241 non-null  float64
 61  BPY_AIR_TEMP_FREQUENCY  1439241 non-null  float64
 62  BPY_ASIC_TEMP           1439226 non-null  float64
dtypes: float64(60), object(3)
memory usage: 1.1+ GB

In [6]:
# I can see I have some missing values, let's see how many in each column:
df.isnull().sum()

AOBT                            0
SCLK                            0
LMST                            0
LTST                            0
UTC                             0
BMY_2L_TEMP_1              910435
BMY_2L_TEMP_2              910435
BMY_2L_TEMP_3              910435
BMY_2L_TEMP_4             1642774
BMY_2L_TEMP_4_AVERAGE     1618112
BMY_2L_TEMP_4_STD         1618112
BMY_2L_TEMP_5              910435
BMY_2L_TEMP_6              910435
BMY_AIR_TEMP              1642774
BMY_AIR_TEMP_AVERAGE      1618112
BMY_AIR_TEMP_STD          1618112
BMY_WD_REF_OUT_1           910435
BMY_WD_REF_OUT_2           910435
BMY_WD_REF_OUT_3           912043
BMY_WD_OUT_1               910435
BMY_WD_OUT_2               910435
BMY_WD_OUT_3               910435
BMY_WD_OUT_4               910435
BMY_WD_OUT_5               911459
BMY_WD_OUT_6               910435
BMY_WD_OUT_7               910435
BMY_WD_OUT_8               910435
BMY_WD_OUT_9               910435
BMY_WD_OUT_10              910435
BMY_WD_OUT_11              911019
BMY_WD_OUT_12              910435
BMY_WIND_FREQUENCY         910435
BMY_AIR_TEMP_FREQUENCY     910435
BMY_ASIC_TEMP              910437
BPY_2L_TEMP_1              911230
BPY_2L_TEMP_2              911230
BPY_2L_TEMP_3              912219
BPY_2L_TEMP_4              911195
BPY_2L_TEMP_5             1643505
BPY_2L_TEMP_5_AVERAGE     1618161
BPY_2L_TEMP_5_STD         1618161
BPY_2L_TEMP_6              911195
BPY_AIR_TEMP              1643505
BPY_AIR_TEMP_AVERAGE      1618161
BPY_AIR_TEMP_STD          1618161
BPY_WD_REF_OUT_1           911195
BPY_WD_REF_OUT_2           911195
BPY_WD_REF_OUT_3           911195
BPY_WD_OUT_1               911195
BPY_WD_OUT_2               912219
BPY_WD_OUT_3               911195
BPY_WD_OUT_4               911195
BPY_WD_OUT_5               911195
BPY_WD_OUT_6               911195
BPY_WD_OUT_7               911195
BPY_WD_OUT_8               911195
BPY_WD_OUT_9               911195
BPY_WD_OUT_10              911195
BPY_WD_OUT_11              911195
BPY_WD_OUT_12              911195
BPY_WIND_FREQUENCY         911195
BPY_AIR_TEMP_FREQUENCY     911195
BPY_ASIC_TEMP              911210
dtype: int64

Looks like I have a lot of missing data to look into. Before I do that tho I think I'll drop some columns first.  
Now I'd like to drop some columns so my data is simple to explore, however I think I should create a data dictionary first so I don't delete anything important!

## TWINS Raw Data Columns
|System          |  # | Column  |Data Type              | Description                                         |
|:---------------|:---|:--------|:----------------------|:----------------------------------------------------|
|Time References |  1 | AOBT    |ASCII_Real             | APSS Onboard Time
|                |  2 | SCLK    |ASCII_Real             | Spacecraft Clock
|                |  3 | LMST    |ASCII_String           | Local Mean Solar Time
|                |  4 | LTST    |ASCII_String           | Local True Solar Time
|                |  5 | UTC     |ASCII_Date_Time_DOY_UTC| Coordinated Universal Time
|================|====|=========|=======================|=====================================================|
| BOOM -Y        |  6 | BMY_2L_TEMP_1 | ASCII_Integer | Wind Sensor transducer 1 Printed Circuit Board temperature PT-1000 Platinum Resistance Thermometer |
|                |  7 | BMY_2L_TEMP_2 | ASCII_Integer | WS transducer 2 PCB temperature PT-1000 PRT | 
|                |  8 | BMY_2L_TEMP_3 | ASCII_Integer | WS transducer 3 PCB temperature PT-1000 PRT |
|                |  9 | BMY_2L_TEMP_4 | ASCII_Integer | ATS-mid-rodtemperature: PT1000 PRT sensor located at an intermediate position in the ATS rod|
|                | 10 | BMY_2L_TEMP_4_AVERAGE | ASCII_Integer | ATS-mid-rod temperature average of the last N samples
|                | 11 | BMY_2L_TEMP_4_STD     | ASCII_Integer | ATS-mid-rod temperature standard deviation of the last N samples
|                | 12 | BMY_2L_TEMP_5         | ASCII_Integer | Boom Housing Temp: PT-1000 PRT located at the Boom housing near the base of the ATS rod
|                | 13 | BMY_2L_TEMP_6         | ASCII_Integer | Calibration resistor: 1K ohm
|                | 14 | BMY_AIR_TEMP | ASCII_Integer | ATS-rod-extreme temperature: PT1000 PRT located at ATS extreme
|                | 15 | BMY_AIR_TEMP_AVERAGE  | ASCII_Integer | ATS-rod-extreme temperature average of the last N samples
|                | 16 | BMY_AIR_TEMP_STD | ASCII_Integer | ATS-rod-extreme temperature standard deviation of the last N samples
|                | 17 | BMY_WD_REF_OUT_1 | ASCII_Integer | WS transducer 1 cold die temperature
|                | 18 | BMY_WD_REF_OUT_2 | ASCII_Integer | WS transducer 2 cold die temperature
|                | 19 | BMY_WD_REF_OUT_3 | ASCII_Integer | WS transducer 3 cold die temperature
|                | 20 | BMY_WD_OUT_1     | ASCII_Integer | Number of counts measured for WS channel 1
|                | 21 | BMY_WD_OUT_2     | ASCII_Integer | Number of counts measured for WS channel 2
|                | 22 | BMY_WD_OUT_3     | ASCII_Integer | Number of counts measured for WS channel 3
|                | 23 | BMY_WD_OUT_4     | ASCII_Integer | Number of counts measured for WS channel 4
|                | 24 | BMY_WD_OUT_5     | ASCII_Integer | Number of counts measured for WS channel 5
|                | 25 | BMY_WD_OUT_6     | ASCII_Integer | Number of counts measured for WS channel 6
|                | 26 | BMY_WD_OUT_7     | ASCII_Integer | Number of counts measured for WS channel 7
|                | 27 | BMY_WD_OUT_8     | ASCII_Integer | Number of counts measured for WS channel 8
|                | 28 | BMY_WD_OUT_9     | ASCII_Integer | Number of counts measured for WS channel 9
|                | 29 | BMY_WD_OUT_10    | ASCII_Integer | Number of counts measured for WS channel 10
|                | 30 | BMY_WD_OUT_11    | ASCII_Integer | Number of counts measured for WS channel 11
|                | 31 | BMY_WD_OUT_12 | ASCII_Integer | Number of counts measured for WS channel 12
|                | 32 | BMY_ASIC_TEMP | ASCII_Integer | ASIC temperature
|                | 33 | BMY_AIR_TEMP_FREQUENCY | ASCII_String | Air temperature channels frequency or frequencies
|                | 34 | BMY_WIND_FREQUENCY | ASCII_String | Wind channels frequency or frequencies
|================|====|=========|=======================|=====================================================|
| BOOM +Y        | 35 | BPY_2L_TEMP_1 | ASCII_Integer | WS transducer 1 PCB temperature PT-1000 PRT
|                | 36 | BPY_2L_TEMP_2 | ASCII_Integer | WS transducer 2 PCB temperature PT-1000 PRT
|                | 37 | BPY_2L_TEMP_3 | ASCII_Integer | WS transducer 3 PCB temperature PT-1000 PRT
|                | 38 | BPY_2L_TEMP_4 | ASCII_Integer | Calibration resistor: 1K ohm
|                | 39 | BPY_2L_TEMP_5 | ASCII_Integer | ATS-mid-rod temperature: PT1000 PRT sensor located at a intermediate position in the ATS rod
|                | 40 | BPY_2L_TEMP_5_AVERAGE | ASCII_Integer | ATS-mid-rod temperature average of the last N samples
|                | 41 | BPY_2L_TEMP_5_STD | ASCII_Integer | ATS-mid-rod temperature standard deviation of the last N samples
|                | 42 | BPY_2L_TEMP_6 | ASCII_Integer | Boom Housing Temp: PT-1000 PRT located at the Boom housing near the base of the ATS rod
|                | 43 | BPY_AIR_TEMP | ASCII_Integer | ATS-rod-extreme temperature: PT1000 PRT located at ATS extreme
|                | 44 | BPY_AIR_TEMP_AVERAGE | ASCII_Integer | ATS-rod-extreme temperature average of the last N samples
|                | 45 | BPY_AIR_TEMP_STD | ASCII_Integer | ATS-rod-extreme temperature standard deviation of the last N samples
|                | 46 | BPY_WD_REF_OUT_1 | ASCII_Integer | WS transducer 1 cold die temperature
|                | 47 | BPY_WD_REF_OUT_2 | ASCII_Integer | WS transducer 2 cold die temperature
|                | 48 | BPY_WD_REF_OUT_3 | ASCII_Integer | WS transducer 3 cold die temperature
|                | 49 | BPY_WD_OUT_1     | ASCII_Integer | Number of counts measured for WS channel 1
|                | 50 | BPY_WD_OUT_2     | ASCII_Integer | Number of counts measured for WS channel 2
|                | 51 | BPY_WD_OUT_3     | ASCII_Integer | Number of counts measured for WS channel 3
|                | 52 | BPY_WD_OUT_4     | ASCII_Integer | Number of counts measured for WS channel 4
|                | 53 | BPY_WD_OUT_5     | ASCII_Integer | Number of counts measured for WS channel 5
|                | 54 | BPY_WD_OUT_6     | ASCII_Integer | Number of counts measured for WS channel 6
|                | 55 | BPY_WD_OUT_7     | ASCII_Integer | Number of counts measured for WS channel 7
|                | 56 | BPY_WD_OUT_8     | ASCII_Integer | Number of counts measured for WS channel 8
|                | 57 | BPY_WD_OUT_9     | ASCII_Integer | Number of counts measured for WS channel 9
|                | 58 | BPY_WD_OUT_10    | ASCII_Integer | Number of counts measured for WS channel 10
|                | 59 | BPY_WD_OUT_11    | ASCII_Integer | Number of counts measured for WS channel 11
|                | 60 | BPY_WD_OUT_12    | ASCII_Integer | Number of counts measured for WS channel 12
|                | 61 | BPY_ASIC_TEMP    | ASCII_Integer | ASIC temperature
|                | 62 | BPY_AIR_TEMP_FREQUENCY | ASCII_String |Air temperature channels frequency or frequencies
|                | 63 | BPY_WIND_FREQUENCY | ASCII_String | Wind channels frequency or frequencies

In [7]:
# df.BPY_AIR_TEMP_FREQUENCY

#### TWINS RAW Data
>In continuous mode, and for mid-rod and extreme-rod air temperature PT1000 sensors, the
recorded value is an average and a standard deviation using a window of N samples (N
defined to 7). This window starts at the time in which the decimation process selects the
rest of the data, each M samples. This means that the actual averages and standard
deviations are obtained N seconds after the rest of the samples. For convenience, the data
products contain all values aligned at the same time tags.  
Air Temperature data for which the average and standard deviations are calculated have
three columns: one for the raw value, for modes in which a single sample was retrieved,
and two others with the average and standard deviations. Depending on the downlink mode
used to retrieve the data, the appropriate column will contain the value and the other(s) will
be empty.

## My plan
BOOM -Y , Take average of all these temps and make one column
- BMY_2L_TEMP_1
- BMY_2L_TEMP_2
- BMY_2L_TEMP_3
- BMY_2L_TEMP_4
- BMY_2L_TEMP_4_AVERAGE [DROP]
- BPY_2L_TEMP_5
- BPY_2L_TEMP_5_AVERAGE [DROP]
- BPY_2L_TEMP_5_STD [DROP]
- BPY_2L_TEMP_6
---
- BMY_AIR_TEMP
- BMY_AIR_TEMP_AVERAGE [DROP]
- BMY_AIR_TEMP_STD [DROP]
---
Take the average of these
- BMY_WD_REF_OUT_1
- BMY_WD_REF_OUT_2
- BMY_WD_REF_OUT_3
---
Take the average of these
- BPY_WD_OUT_1
- BPY_WD_OUT_2
- BPY_WD_OUT_3
- BPY_WD_OUT_4
- BPY_WD_OUT_5
- BPY_WD_OUT_6
- BPY_WD_OUT_7
- BPY_WD_OUT_8
- BPY_WD_OUT_9
- BPY_WD_OUT_10
- BPY_WD_OUT_11
- BPY_WD_OUT_12
---
- BMY_ASIC_TEMP
- BPY_AIR_TEMP_FREQUENCY
- BPY_WIND_FREQUENCY

BOOM +Y
- BPY_2L_TEMP_1
- BPY_2L_TEMP_2
- BPY_2L_TEMP_3
- BPY_2L_TEMP_4
- BPY_2L_TEMP_5
- BPY_2L_TEMP_5_AVERAGE
- BPY_2L_TEMP_5_STD
- BPY_2L_TEMP_6
---
- BPY_AIR_TEMP
- BPY_AIR_TEMP_AVERAGE
- BPY_AIR_TEMP_STD
---
- BPY_WD_REF_OUT_1
- BPY_WD_REF_OUT_2
- BPY_WD_REF_OUT_3
---
- BPY_WD_OUT_1
- BPY_WD_OUT_2
- BPY_WD_OUT_3
- BPY_WD_OUT_4
- BPY_WD_OUT_5
- BPY_WD_OUT_6
- BPY_WD_OUT_7
- BPY_WD_OUT_8
- BPY_WD_OUT_9
- BPY_WD_OUT_10
- BPY_WD_OUT_11
- BPY_WD_OUT_12
---
- BPY_ASIC_TEMP
- BPY_AIR_TEMP_FREQUENCY
- BPY_WIND_FREQUENCY

In [10]:
df.head()

,AOBT,SCLK,LMST,LTST,UTC,BMY_2L_TEMP_1,BMY_2L_TEMP_2,BMY_2L_TEMP_3,BMY_2L_TEMP_4,BMY_2L_TEMP_4_AVERAGE,BMY_2L_TEMP_4_STD,BMY_2L_TEMP_5,BMY_2L_TEMP_6,BMY_AIR_TEMP,BMY_AIR_TEMP_AVERAGE,BMY_AIR_TEMP_STD,BMY_WD_REF_OUT_1,BMY_WD_REF_OUT_2,BMY_WD_REF_OUT_3,BMY_WD_OUT_1,BMY_WD_OUT_2,BMY_WD_OUT_3,BMY_WD_OUT_4,BMY_WD_OUT_5,BMY_WD_OUT_6,BMY_WD_OUT_7,BMY_WD_OUT_8,BMY_WD_OUT_9,BMY_WD_OUT_10,BMY_WD_OUT_11,BMY_WD_OUT_12,BMY_WIND_FREQUENCY,BMY_AIR_TEMP_FREQUENCY,BMY_ASIC_TEMP,BPY_2L_TEMP_1,BPY_2L_TEMP_2,BPY_2L_TEMP_3,BPY_2L_TEMP_4,BPY_2L_TEMP_5,BPY_2L_TEMP_5_AVERAGE,BPY_2L_TEMP_5_STD,BPY_2L_TEMP_6,BPY_AIR_TEMP,BPY_AIR_TEMP_AVERAGE,BPY_AIR_TEMP_STD,BPY_WD_REF_OUT_1,BPY_WD_REF_OUT_2,BPY_WD_REF_OUT_3,BPY_WD_OUT_1,BPY_WD_OUT_2,BPY_WD_OUT_3,BPY_WD_OUT_4,BPY_WD_OUT_5,BPY_WD_OUT_6,BPY_WD_OUT_7,BPY_WD_OUT_8,BPY_WD_OUT_9,BPY_WD_OUT_10,BPY_WD_OUT_11,BPY_WD_OUT_12,BPY_WIND_FREQUENCY,BPY_AIR_TEMP_FREQUENCY,BPY_ASIC_TEMP
0,596876952.0,5.968612e+08,00004M06:46:33.826,00004 06:05:41,2018-334T14:46:55.755Z,-4353.0,-4645.0,-4778.0,-5006.0,NaN,NaN,-4512.0,1002.0,-5703.0,NaN,NaN,4369.0,5167.0,5599.0,648.0,662.0,648.0,1687.0,3360.0,1109.0,1019.0,1229.0,868.0,2451.0,760.0,663.0,1.0,1.0,8485.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,596876953.0,5.968612e+08,00004M06:46:34.799,00004 06:05:42,2018-334T14:46:56.755Z,-4415.0,-4723.0,-4870.0,-5099.0,NaN,NaN,-4600.0,936.0,-5776.0,NaN,NaN,4274.0,5108.0,5524.0,867.0,379.0,828.0,1033.0,10.0,551.0,578.0,324.0,637.0,418.0,526.0,492.0,1.0,1.0,8488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,596876954.0,5.968612e+08,00004M06:46:35.772,00004 06:05:43,2018-334T14:46:57.755Z,-4424.0,-4727.0,-4861.0,-5107.0,NaN,NaN,-4613.0,930.0,-5803.0,NaN,NaN,4301.0,5100.0,5532.0,713.0,521.0,641.0,1085.0,1194.0,855.0,807.0,918.0,859.0,1233.0,741.0,661.0,1.0,1.0,8491.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,596876955.0,5.968612e+08,00004M06:46:36.746,00004 06:05:44,2018-334T14:46:58.755Z,-4409.0,-4722.0,-4859.0,-5109.0,NaN,NaN,-4603.0,916.0,-5771.0,NaN,NaN,4297.0,5111.0,5539.0,687.0,578.0,662.0,1028.0,1254.0,861.0,857.0,991.0,879.0,1190.0,717.0,689.0,1.0,1.0,8494.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,596876956.0,5.968612e+08,00004M06:46:37.719,00004 06:05:45,2018-334T14:46:59.755Z,-4424.0,-4728.0,-4873.0,-5107.0,NaN,NaN,-4610.0,922.0,-5754.0,NaN,NaN,4296.0,5113.0,5535.0,438.0,284.0,599.0,862.0,1085.0,748.0,969.0,1049.0,813.0,1097.0,417.0,443.0,1.0,1.0,8498.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

During science monitoring phase, after all instruments (SEIS, HP3) are deployed, only one
boom will be used at a time. A selection of which boom is operative (measuring) will be
done in accordance to where the wind flows come from, highly determined by the time of
the Martian day (among other factors). The boom selection pattern will be commanded
once per week, based on past observations and predictive models

In [13]:
# If I'm being honest there's a lot of overwhelming data here
# So I'm gonna break it down...
# I'll start by making time into a dataframe
time = df[['AOBT', 'SCLK', 'LMST', 'LTST', 'UTC']].head()
time.head()

,AOBT,SCLK,LMST,LTST,UTC
0,596876952.0,5.968612e+08,00004M06:46:33.826,00004 06:05:41,2018-334T14:46:55.755Z
1,596876953.0,5.968612e+08,00004M06:46:34.799,00004 06:05:42,2018-334T14:46:56.755Z
2,596876954.0,5.968612e+08,00004M06:46:35.772,00004 06:05:43,2018-334T14:46:57.755Z
3,596876955.0,5.968612e+08,00004M06:46:36.746,00004 06:05:44,2018-334T14:46:58.755Z
4,596876956.0,5.968612e+08,00004M06:46:37.719,00004 06:05:45,2018-334T14:46:59.755Z

In [16]:
# Now to separate and examine the BMY_2L_TEMP data
# Why does TEMP 6 have positive numbers?
BMY_2L_Temp = df[['BMY_2L_TEMP_1', 'BMY_2L_TEMP_2', 'BMY_2L_TEMP_3', 'BMY_2L_TEMP_4', 'BMY_2L_TEMP_5', 'BMY_2L_TEMP_6']]
BMY_2L_Temp.head()

,BMY_2L_TEMP_1,BMY_2L_TEMP_2,BMY_2L_TEMP_3,BMY_2L_TEMP_4,BMY_2L_TEMP_5,BMY_2L_TEMP_6
0,-4353.0,-4645.0,-4778.0,-5006.0,-4512.0,1002.0
1,-4415.0,-4723.0,-4870.0,-5099.0,-4600.0,936.0
2,-4424.0,-4727.0,-4861.0,-5107.0,-4613.0,930.0
3,-4409.0,-4722.0,-4859.0,-5109.0,-4603.0,916.0
4,-4424.0,-4728.0,-4873.0,-5107.0,-4610.0,922.0

In [18]:
# I know it's simple but I want to separate EVERYTHING
BMY_AIR_TEMP = df.BMY_AIR_TEMP
BMY_AIR_TEMP.head()

0   -5703.0
1   -5776.0
2   -5803.0
3   -5771.0
4   -5754.0
Name: BMY_AIR_TEMP, dtype: float64

In [20]:
# Boom Minus Y reference out = Wind Speed transducer cold die temperature
BMY_WD_REF_OUT = df[['BMY_WD_REF_OUT_1', 'BMY_WD_REF_OUT_2', 'BMY_WD_REF_OUT_3']]
BMY_WD_REF_OUT.head()

   BMY_WD_REF_OUT_1  BMY_WD_REF_OUT_2  BMY_WD_REF_OUT_3
0            4369.0            5167.0            5599.0
1            4274.0            5108.0            5524.0
2            4301.0            5100.0            5532.0
3            4297.0            5111.0            5539.0
4            4296.0            5113.0            5535.0

In [22]:
# Boom Minus Y Wind Direction OUT = Number of counts measured for Wind Speed channel #
BMY_WD_OUT = df[['BMY_WD_OUT_1', 'BMY_WD_OUT_2', 'BMY_WD_OUT_3', 'BMY_WD_OUT_4', 'BMY_WD_OUT_5', 'BMY_WD_OUT_6', 'BMY_WD_OUT_7', 'BMY_WD_OUT_8', 'BMY_WD_OUT_9', 'BMY_WD_OUT_10', 'BMY_WD_OUT_11',  'BMY_WD_OUT_12']]
BMY_WD_OUT.head()

,BMY_WD_OUT_1,BMY_WD_OUT_2,BMY_WD_OUT_3,BMY_WD_OUT_4,BMY_WD_OUT_5,BMY_WD_OUT_6,BMY_WD_OUT_7,BMY_WD_OUT_8,BMY_WD_OUT_9,BMY_WD_OUT_10,BMY_WD_OUT_11,BMY_WD_OUT_12
0,648.0,662.0,648.0,1687.0,3360.0,1109.0,1019.0,1229.0,868.0,2451.0,760.0,663.0
1,867.0,379.0,828.0,1033.0,10.0,551.0,578.0,324.0,637.0,418.0,526.0,492.0
2,713.0,521.0,641.0,1085.0,1194.0,855.0,807.0,918.0,859.0,1233.0,741.0,661.0
3,687.0,578.0,662.0,1028.0,1254.0,861.0,857.0,991.0,879.0,1190.0,717.0,689.0
4,438.0,284.0,599.0,862.0,1085.0,748.0,969.0,1049.0,813.0,1097.0,417.0,443.0

In [26]:
frequency = df[['BMY_WIND_FREQUENCY', 'BMY_AIR_TEMP_FREQUENCY']]
BMY_ASIC_TEMP = df.BMY_ASIC_TEMP

In [28]:
BPY_2L_TEMP = df[['BPY_2L_TEMP_1', 'BPY_2L_TEMP_2', 'BPY_2L_TEMP_3', 'BPY_2L_TEMP_4', 'BPY_2L_TEMP_5', 'BPY_2L_TEMP_6']]
BPY_AIR_TEMP = df.BPY_AIR_TEMP
BPY_WD_REF_OUT = df[['BPY_WD_REF_OUT_1', 'BPY_WD_REF_OUT_2', 'BPY_WD_REF_OUT_3']]
BPY_WD_OUT = df[['BPY_WD_OUT_1', 'BPY_WD_OUT_2', 'BPY_WD_OUT_3', 'BPY_WD_OUT_4', 'BPY_WD_OUT_5', 'BPY_WD_OUT_6', 'BPY_WD_OUT_7', 'BPY_WD_OUT_8', 'BPY_WD_OUT_9', 'BPY_WD_OUT_10', 'BPY_WD_OUT_11', 'BPY_WD_OUT_12']]
BPY_FREQUENCY = df[['BPY_WIND_FREQUENCY', 'BPY_AIR_TEMP_FREQUENCY']]
BPY_ASIC_TEMP = df.BPY_ASIC_TEMP

In [25]:
df.BMY_AIR_TEMP_FREQUENCY.value_counts()

0.1    732339
0.5    690182
1.0     17480
Name: BMY_AIR_TEMP_FREQUENCY, dtype: int64

In [32]:
# I don't know why temp 6 is a positive number
# Temp 6 is for the Calibration resistor: 1K ohm
# I will drop it from the average 
BMY_2L_Temp['BMY_2L_TEMP_AVG'] = (BMY_2L_Temp.BMY_2L_TEMP_1 + BMY_2L_Temp.BMY_2L_TEMP_2 + BMY_2L_Temp.BMY_2L_TEMP_3 + BMY_2L_Temp.BMY_2L_TEMP_4 + BMY_2L_Temp.BMY_2L_TEMP_5)/5
BMY_2L_Temp.head()

,BMY_2L_TEMP_1,BMY_2L_TEMP_2,BMY_2L_TEMP_3,BMY_2L_TEMP_4,BMY_2L_TEMP_5,BMY_2L_TEMP_6,BMY_2L_TEMP_AVG
0,-4353.0,-4645.0,-4778.0,-5006.0,-4512.0,1002.0,-4658.8
1,-4415.0,-4723.0,-4870.0,-5099.0,-4600.0,936.0,-4741.4
2,-4424.0,-4727.0,-4861.0,-5107.0,-4613.0,930.0,-4746.4
3,-4409.0,-4722.0,-4859.0,-5109.0,-4603.0,916.0,-4740.4
4,-4424.0,-4728.0,-4873.0,-5107.0,-4610.0,922.0,-4748.4

In [54]:
# Wind Speed transducer cold die temperature
# I am going to make a column for the average of the 3 transducers
BMY_WD_REF_OUT['BMY_WD_REF_OUT_AVG'] = (BMY_WD_REF_OUT.BMY_WD_REF_OUT_1 + BMY_WD_REF_OUT.BMY_WD_REF_OUT_2 + BMY_WD_REF_OUT.BMY_WD_REF_OUT_3)/3
BMY_WD_REF_OUT.head()

,BMY_WD_REF_OUT_1,BMY_WD_REF_OUT_2,BMY_WD_REF_OUT_3,average,BMY_WD_REF_OUT_AVG
0,4369.0,5167.0,5599.0,5045.000000,5045.000000
1,4274.0,5108.0,5524.0,4968.666667,4968.666667
2,4301.0,5100.0,5532.0,4977.666667,4977.666667
3,4297.0,5111.0,5539.0,4982.333333,4982.333333
4,4296.0,5113.0,5535.0,4981.333333,4981.333333

In [48]:
# should i keep them separate or combine them with a loop where it takes the column without null 
# or averages if both columns have data?
temp = pd.concat([BMY_AIR_TEMP , BPY_AIR_TEMP], axis=1)
temp.head()

   BMY_AIR_TEMP  BPY_AIR_TEMP
0       -5703.0           NaN
1       -5776.0           NaN
2       -5803.0           NaN
3       -5771.0           NaN
4       -5754.0           NaN

In [49]:
# This is wind direction. I'm not sure I can calculate this in my MVP, so I think I'll leave this out for now
# I'll come back for this later
BMY_WD_OUT.head()

,BMY_WD_OUT_1,BMY_WD_OUT_2,BMY_WD_OUT_3,BMY_WD_OUT_4,BMY_WD_OUT_5,BMY_WD_OUT_6,BMY_WD_OUT_7,BMY_WD_OUT_8,BMY_WD_OUT_9,BMY_WD_OUT_10,BMY_WD_OUT_11,BMY_WD_OUT_12
0,648.0,662.0,648.0,1687.0,3360.0,1109.0,1019.0,1229.0,868.0,2451.0,760.0,663.0
1,867.0,379.0,828.0,1033.0,10.0,551.0,578.0,324.0,637.0,418.0,526.0,492.0
2,713.0,521.0,641.0,1085.0,1194.0,855.0,807.0,918.0,859.0,1233.0,741.0,661.0
3,687.0,578.0,662.0,1028.0,1254.0,861.0,857.0,991.0,879.0,1190.0,717.0,689.0
4,438.0,284.0,599.0,862.0,1085.0,748.0,969.0,1049.0,813.0,1097.0,417.0,443.0

In [50]:
# Air temperature channels frequency or frequencies
# Wind channels frequency or frequencies
# I don't think I need to know what frequency channel they were using at the time
# Not using in MVP 
frequency.head()

   BMY_WIND_FREQUENCY  BMY_AIR_TEMP_FREQUENCY
0                 1.0                     1.0
1                 1.0                     1.0
2                 1.0                     1.0
3                 1.0                     1.0
4                 1.0                     1.0

In [55]:
BMY_simple_df = pd.concat([BMY_2L_Temp.BMY_2L_TEMP_AVG, # temperature
                           BMY_AIR_TEMP, # temperature
                           BMY_WD_REF_OUT.BMY_WD_REF_OUT_AVG, # temperature
                           BMY_ASIC_TEMP # temperature
                          ], axis=1)

BMY_simple_df.head()

   BMY_2L_TEMP_AVG  BMY_AIR_TEMP  BMY_WD_REF_OUT_AVG  BMY_ASIC_TEMP
0          -4658.8       -5703.0         5045.000000         8485.0
1          -4741.4       -5776.0         4968.666667         8488.0
2          -4746.4       -5803.0         4977.666667         8491.0
3          -4740.4       -5771.0         4982.333333         8494.0
4          -4748.4       -5754.0         4981.333333         8498.0

In [60]:
# BPY_2L_TEMP_4 is the resistor, so I'll skip that for averaging again
BPY_2L_TEMP['BPY_2L_TEMP_AVG'] = (BPY_2L_TEMP.BPY_2L_TEMP_1 + BPY_2L_TEMP.BPY_2L_TEMP_2 + BPY_2L_TEMP.BPY_2L_TEMP_3 + BPY_2L_TEMP.BPY_2L_TEMP_5 + BPY_2L_TEMP.BPY_2L_TEMP_6)/5
BPY_2L_TEMP.head(100)

,BPY_2L_TEMP_1,BPY_2L_TEMP_2,BPY_2L_TEMP_3,BPY_2L_TEMP_4,BPY_2L_TEMP_5,BPY_2L_TEMP_6,BPY_2L_TEMP_AVG
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,-2835.0,-2401.0,-1998.0,1774.0,-2130.0,-2112.0,-2295.2
90,-2941.0,-2487.0,-2079.0,1682.0,-2250.0,-2199.0,-2391.2
91,-2923.0,-2484.0,-2091.0,1696.0,-2248.0,-2199.0,-2389.0
92,-2930.0,-2456.0,-2081.0,1685.0,-2238.0,-2197.0,-2380.4
93,-2918.0,-2464.0,-2070.0,1686.0,-2232.0,-2196.0,-2376.0
94,-2908.0,-2450.0,-2046.0,1700.0,-2230.0,-2188.0,-2364.4
95,-2915.0,-2463.0,-2062.0,1682.0,-2242.0,-2201.0,-2376.6
96,-2896.0,-2453.0,-2055.0,1703.0,-2228.0,-2193.0,-2365.0
97,-2887.0,-2441.0,-2054.0,1709.0,-2229.0,-2177.0,-2357.6
98,-2908.0,-2444.0,-2048.0,1685.0,-2218.0,-2185.0,-2360.6
99,-2872.0,-2422.0,-2039.0,1699.0,-2210.0,-2167.0,-2342.0

In [63]:
# 
BPY_WD_REF_OUT['BPY_WD_REF_OUT_AVG'] = (BPY_WD_REF_OUT.BPY_WD_REF_OUT_1 + BPY_WD_REF_OUT.BPY_WD_REF_OUT_2 + BPY_WD_REF_OUT.BPY_WD_REF_OUT_3)/3

BPY_WD_REF_OUT.head(100)

    BPY_WD_REF_OUT_1  BPY_WD_REF_OUT_2  BPY_WD_REF_OUT_3  BPY_WD_REF_OUT_AVG
0                NaN               NaN               NaN                 NaN
1                NaN               NaN               NaN                 NaN
2                NaN               NaN               NaN                 NaN
3                NaN               NaN               NaN                 NaN
4                NaN               NaN               NaN                 NaN
5                NaN               NaN               NaN                 NaN
6                NaN               NaN               NaN                 NaN
7                NaN               NaN               NaN                 NaN
8                NaN               NaN               NaN                 NaN
9                NaN               NaN               NaN                 NaN
10               NaN               NaN               NaN                 NaN
11               NaN               NaN               NaN                 NaN
12               NaN               NaN               NaN                 NaN
13               NaN               NaN               NaN                 NaN
14               NaN               NaN               NaN                 NaN
15               NaN               NaN               NaN                 NaN
16               NaN               NaN               NaN                 NaN
17               NaN               NaN               NaN                 NaN
18               NaN               NaN               NaN                 NaN
19               NaN               NaN               NaN                 NaN
20               NaN               NaN               NaN                 NaN
21               NaN               NaN               NaN                 NaN
22               NaN               NaN               NaN                 NaN
23               NaN               NaN               NaN                 NaN
24               NaN               NaN               NaN                 NaN
25               NaN               NaN               NaN                 NaN
26               NaN               NaN               NaN                 NaN
27               NaN               NaN               NaN                 NaN
28               NaN               NaN               NaN                 NaN
29               NaN               NaN               NaN                 NaN
30               NaN               NaN               NaN                 NaN
31               NaN               NaN               NaN                 NaN
32               NaN               NaN               NaN                 NaN
33               NaN               NaN               NaN                 NaN
34               NaN               NaN               NaN                 NaN
35               NaN               NaN               NaN                 NaN
36               NaN               NaN               NaN                 NaN
37               NaN               NaN               NaN                 NaN
38               NaN               NaN               NaN                 NaN
39               NaN               NaN               NaN                 NaN
40               NaN               NaN               NaN                 NaN
41               NaN               NaN               NaN                 NaN
42               NaN               NaN               NaN                 NaN
43               NaN               NaN               NaN                 NaN
44               NaN               NaN               NaN                 NaN
45               NaN               NaN               NaN                 NaN
46               NaN               NaN               NaN                 NaN
47               NaN               NaN               NaN                 NaN
48               NaN               NaN               NaN                 NaN
49               NaN               NaN               NaN                 NaN
50               NaN               NaN               NaN                 NaN
51               NaN               NaN               NaN                 NaN
52               NaN               NaN               NaN                 NaN
53               NaN               NaN               NaN                 NaN
54               NaN               NaN               NaN                 NaN
55               NaN               NaN               NaN                 NaN
56               NaN               NaN               NaN                 NaN
57               NaN               NaN               NaN                 NaN
58               NaN               NaN               NaN                 NaN
59               NaN               NaN               NaN                 NaN
60               NaN               NaN               NaN                 NaN
61               NaN               NaN               NaN                 NaN
62               NaN               NaN               NaN                 NaN
63               NaN               NaN               NaN                 NaN
64               NaN               NaN               NaN                 NaN
65               NaN               NaN               NaN                 NaN
66               NaN               NaN               NaN                 NaN
67               NaN               NaN               NaN                 NaN
68               NaN               NaN               NaN                 NaN
69               NaN               NaN               NaN                 NaN
70               NaN               NaN               NaN                 NaN
71               NaN               NaN               NaN                 NaN
72               NaN               NaN               NaN                 NaN
73               NaN               NaN               NaN                 NaN
74               NaN               NaN               NaN                 NaN
75               NaN               NaN               NaN                 NaN
76               NaN               NaN               NaN                 NaN
77               NaN               NaN               NaN                 NaN
78               NaN               NaN               NaN                 NaN
79               NaN               NaN               NaN                 NaN
80               NaN               NaN               NaN                 NaN
81               NaN               NaN               NaN                 NaN
82               NaN               NaN               NaN                 NaN
83               NaN               NaN               NaN                 NaN
84               NaN               NaN               NaN                 NaN
85               NaN               NaN               NaN                 NaN
86               NaN               NaN               NaN                 NaN
87               NaN               NaN               NaN                 NaN
88               NaN               NaN               NaN                 NaN
89           10543.0            9973.0           10370.0        10295.333333
90           10491.0            9997.0           10386.0        10291.333333
91           10512.0           10027.0           10405.0        10314.666667
92           10496.0           10022.0           10381.0        10299.666667
93           10499.0           10016.0           10376.0        10297.000000
94           10506.0           10047.0           10398.0        10317.000000
95           10521.0           10048.0           10397.0        10322.000000
96           10521.0           10048.0           10401.0        10323.333333
97           10522.0           10042.0           10409.0        10324.333333
98           10532.0           10019.0           10407.0        10319.333333
99           10562.0           10037.0           10405.0        10334.666667

In [64]:
BPY_simple_df = pd.concat([BPY_2L_TEMP.BPY_2L_TEMP_AVG, # temperature
                           BPY_AIR_TEMP, # temperature
                           BPY_WD_REF_OUT.BPY_WD_REF_OUT_AVG, # temperature
                           BPY_ASIC_TEMP # temperature
                          ], axis=1)
BPY_simple_df.head(100)

    BPY_2L_TEMP_AVG  BPY_AIR_TEMP  BPY_WD_REF_OUT_AVG  BPY_ASIC_TEMP
0               NaN           NaN                 NaN            NaN
1               NaN           NaN                 NaN            NaN
2               NaN           NaN                 NaN            NaN
3               NaN           NaN                 NaN            NaN
4               NaN           NaN                 NaN            NaN
5               NaN           NaN                 NaN            NaN
6               NaN           NaN                 NaN            NaN
7               NaN           NaN                 NaN            NaN
8               NaN           NaN                 NaN            NaN
9               NaN           NaN                 NaN            NaN
10              NaN           NaN                 NaN            NaN
11              NaN           NaN                 NaN            NaN
12              NaN           NaN                 NaN            NaN
13              NaN           NaN                 NaN            NaN
14              NaN           NaN                 NaN            NaN
15              NaN           NaN                 NaN            NaN
16              NaN           NaN                 NaN            NaN
17              NaN           NaN                 NaN            NaN
18              NaN           NaN                 NaN            NaN
19              NaN           NaN                 NaN            NaN
20              NaN           NaN                 NaN            NaN
21              NaN           NaN                 NaN            NaN
22              NaN           NaN                 NaN            NaN
23              NaN           NaN                 NaN            NaN
24              NaN           NaN                 NaN            NaN
25              NaN           NaN                 NaN            NaN
26              NaN           NaN                 NaN            NaN
27              NaN           NaN                 NaN            NaN
28              NaN           NaN                 NaN            NaN
29              NaN           NaN                 NaN            NaN
30              NaN           NaN                 NaN            NaN
31              NaN           NaN                 NaN            NaN
32              NaN           NaN                 NaN            NaN
33              NaN           NaN                 NaN            NaN
34              NaN           NaN                 NaN            NaN
35              NaN           NaN                 NaN            NaN
36              NaN           NaN                 NaN            NaN
37              NaN           NaN                 NaN            NaN
38              NaN           NaN                 NaN            NaN
39              NaN           NaN                 NaN            NaN
40              NaN           NaN                 NaN            NaN
41              NaN           NaN                 NaN            NaN
42              NaN           NaN                 NaN            NaN
43              NaN           NaN                 NaN            NaN
44              NaN           NaN                 NaN            NaN
45              NaN           NaN                 NaN            NaN
46              NaN           NaN                 NaN            NaN
47              NaN           NaN                 NaN            NaN
48              NaN           NaN                 NaN            NaN
49              NaN           NaN                 NaN            NaN
50              NaN           NaN                 NaN            NaN
51              NaN           NaN                 NaN            NaN
52              NaN           NaN                 NaN            NaN
53              NaN           NaN                 NaN            NaN
54              NaN           NaN                 NaN            NaN
55              NaN           NaN                 NaN            NaN
56              NaN           NaN                 NaN            NaN
57              NaN           NaN                 NaN            NaN
58              NaN           NaN                 NaN            NaN
59              NaN           NaN                 NaN            NaN
60              NaN           NaN                 NaN            NaN
61              NaN           NaN                 NaN            NaN
62              NaN           NaN                 NaN            NaN
63              NaN           NaN                 NaN            NaN
64              NaN           NaN                 NaN            NaN
65              NaN           NaN                 NaN            NaN
66              NaN           NaN                 NaN            NaN
67              NaN           NaN                 NaN            NaN
68              NaN           NaN                 NaN            NaN
69              NaN           NaN                 NaN            NaN
70              NaN           NaN                 NaN            NaN
71              NaN           NaN                 NaN            NaN
72              NaN           NaN                 NaN            NaN
73              NaN           NaN                 NaN            NaN
74              NaN           NaN                 NaN            NaN
75              NaN           NaN                 NaN            NaN
76              NaN           NaN                 NaN            NaN
77              NaN           NaN                 NaN            NaN
78              NaN           NaN                 NaN            NaN
79              NaN           NaN                 NaN            NaN
80              NaN           NaN                 NaN            NaN
81              NaN           NaN                 NaN            NaN
82              NaN           NaN                 NaN            NaN
83              NaN           NaN                 NaN            NaN
84              NaN           NaN                 NaN            NaN
85              NaN           NaN                 NaN            NaN
86              NaN           NaN                 NaN            NaN
87              NaN           NaN                 NaN            NaN
88              NaN           NaN                 NaN            NaN
89          -2295.2       -2156.0        10295.333333         8861.0
90          -2391.2       -2268.0        10291.333333         8866.0
91          -2389.0       -2223.0        10314.666667         8870.0
92          -2380.4       -2232.0        10299.666667         8873.0
93          -2376.0       -2240.0        10297.000000         8878.0
94          -2364.4       -2224.0        10317.000000         8883.0
95          -2376.6       -2238.0        10322.000000         8886.0
96          -2365.0       -2216.0        10323.333333         8892.0
97          -2357.6       -2202.0        10324.333333         8895.0
98          -2360.6       -2227.0        10319.333333         8900.0
99          -2342.0       -2221.0        10334.666667         8904.0

In [65]:
df.head()

,AOBT,SCLK,LMST,LTST,UTC,BMY_2L_TEMP_1,BMY_2L_TEMP_2,BMY_2L_TEMP_3,BMY_2L_TEMP_4,BMY_2L_TEMP_4_AVERAGE,BMY_2L_TEMP_4_STD,BMY_2L_TEMP_5,BMY_2L_TEMP_6,BMY_AIR_TEMP,BMY_AIR_TEMP_AVERAGE,BMY_AIR_TEMP_STD,BMY_WD_REF_OUT_1,BMY_WD_REF_OUT_2,BMY_WD_REF_OUT_3,BMY_WD_OUT_1,BMY_WD_OUT_2,BMY_WD_OUT_3,BMY_WD_OUT_4,BMY_WD_OUT_5,BMY_WD_OUT_6,BMY_WD_OUT_7,BMY_WD_OUT_8,BMY_WD_OUT_9,BMY_WD_OUT_10,BMY_WD_OUT_11,BMY_WD_OUT_12,BMY_WIND_FREQUENCY,BMY_AIR_TEMP_FREQUENCY,BMY_ASIC_TEMP,BPY_2L_TEMP_1,BPY_2L_TEMP_2,BPY_2L_TEMP_3,BPY_2L_TEMP_4,BPY_2L_TEMP_5,BPY_2L_TEMP_5_AVERAGE,BPY_2L_TEMP_5_STD,BPY_2L_TEMP_6,BPY_AIR_TEMP,BPY_AIR_TEMP_AVERAGE,BPY_AIR_TEMP_STD,BPY_WD_REF_OUT_1,BPY_WD_REF_OUT_2,BPY_WD_REF_OUT_3,BPY_WD_OUT_1,BPY_WD_OUT_2,BPY_WD_OUT_3,BPY_WD_OUT_4,BPY_WD_OUT_5,BPY_WD_OUT_6,BPY_WD_OUT_7,BPY_WD_OUT_8,BPY_WD_OUT_9,BPY_WD_OUT_10,BPY_WD_OUT_11,BPY_WD_OUT_12,BPY_WIND_FREQUENCY,BPY_AIR_TEMP_FREQUENCY,BPY_ASIC_TEMP
0,596876952.0,5.968612e+08,00004M06:46:33.826,00004 06:05:41,2018-334T14:46:55.755Z,-4353.0,-4645.0,-4778.0,-5006.0,NaN,NaN,-4512.0,1002.0,-5703.0,NaN,NaN,4369.0,5167.0,5599.0,648.0,662.0,648.0,1687.0,3360.0,1109.0,1019.0,1229.0,868.0,2451.0,760.0,663.0,1.0,1.0,8485.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,596876953.0,5.968612e+08,00004M06:46:34.799,00004 06:05:42,2018-334T14:46:56.755Z,-4415.0,-4723.0,-4870.0,-5099.0,NaN,NaN,-4600.0,936.0,-5776.0,NaN,NaN,4274.0,5108.0,5524.0,867.0,379.0,828.0,1033.0,10.0,551.0,578.0,324.0,637.0,418.0,526.0,492.0,1.0,1.0,8488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,596876954.0,5.968612e+08,00004M06:46:35.772,00004 06:05:43,2018-334T14:46:57.755Z,-4424.0,-4727.0,-4861.0,-5107.0,NaN,NaN,-4613.0,930.0,-5803.0,NaN,NaN,4301.0,5100.0,5532.0,713.0,521.0,641.0,1085.0,1194.0,855.0,807.0,918.0,859.0,1233.0,741.0,661.0,1.0,1.0,8491.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,596876955.0,5.968612e+08,00004M06:46:36.746,00004 06:05:44,2018-334T14:46:58.755Z,-4409.0,-4722.0,-4859.0,-5109.0,NaN,NaN,-4603.0,916.0,-5771.0,NaN,NaN,4297.0,5111.0,5539.0,687.0,578.0,662.0,1028.0,1254.0,861.0,857.0,991.0,879.0,1190.0,717.0,689.0,1.0,1.0,8494.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,596876956.0,5.968612e+08,00004M06:46:37.719,00004 06:05:45,2018-334T14:46:59.755Z,-4424.0,-4728.0,-4873.0,-5107.0,NaN,NaN,-4610.0,922.0,-5754.0,NaN,NaN,4296.0,5113.0,5535.0,438.0,284.0,599.0,862.0,1085.0,748.0,969.0,1049.0,813.0,1097.0,417.0,443.0,1.0,1.0,8498.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
# Is there an overlap where BMY and BPY are collecting data at the same time?
# YES!
df[['BMY_2L_TEMP_1', 'BPY_2L_TEMP_1']].isnull().sum(axis=1).value_counts()

1    1821589
0     528809
2         38
dtype: int64

Translation:  
True + False = 1: There is only one column that has data (is not null)  
False + False = 0: Both columns have data, (niether is null)  
True + True = 2: Neither column has any recorded data (both are null)

SyntaxError: cannot assign to True (1770609971.py, line 1)

Takeaways:
- BMY = Boom minus Y
- BPY = Boom plus Y

- There are so columns simply for telling time! The on board APSS time, the Universal time, local time, etc.
- I want to predict Air Temperature and Wind speed/direction